-- CreateEnum
CREATE TYPE "ItemStatus" AS ENUM ('PENDIENTE_CLASIFICACION', 'EN_STOCK', 'REQUIERE_COMPRA', 'PENDIENTE_VALIDACION_ADMIN', 'APROBADO_COMPRA', 'RECHAZADO_COMPRA', 'LISTO_PARA_DESPACHO', 'DESPACHO_PARCIAL', 'DESPACHADO');

-- AlterTable
ALTER TABLE "requerimiento_items" ADD COLUMN     "estadoItem" "ItemStatus" NOT NULL DEFAULT 'PENDIENTE_CLASIFICACION';
